### ISSUE TITLE
Not finding solution

### ISSUE THREAD

**Issue by micronaut** [ColinEberhardt/wasm-sudoku-solver#3]
Hi Colin.  This is awesome!  I'm trying to get this to work but it doesn't appear to be finding a solution for the sudoko puzzles I am using.  I am using the puzzles from here https://www.memory-improvement-tips.com/printable-sudoku-puzzles-easy-1b.html.  Is there something I have to do in order to train the network?  Thanks!

**Comment by ColinEberhardt** [comment]
Hi @micronaut - I think in that case the thickness of the outer border is causing issues when trying to find the grid cells.

**Comment by micronaut** [comment]
Ok, thanks @ColinEberhardt. I will try some other puzzles.
